[package]
name = "egui_dock"
description = "Docking system for egui - an immediate-mode GUI library for Rust"
authors = ["lain-dono", "Adam Gąsior (Adanos020)"]
version = "0.10.0"
edition = "2021"
rust-version = "1.72"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Adanos020/egui_dock"
categories = ["gui", "game-development"]
include = ["src/**/*.rs", "Cargo.toml", "LICENSE"]

[features]
default = []

# Enable serialization of `Tree`.
serde = ["dep:serde", "egui/serde"]

[dependencies]
egui = { git = "https://github.com/emilk/egui.git", rev = "2c837d25a223b51500661a29c9b76b8fb2598454" , default-features = false }
serde = { version = "1", optional = true, features = ["derive"] }

duplicate = "1.0"
paste = "1.0"

[dev-dependencies]
eframe = { git = "https://github.com/emilk/egui.git", rev = "2c837d25a223b51500661a29c9b76b8fb2598454" , default-features = false, features = [
    "default_fonts",
    "glow",
] }
